In [4]:
import pandas as pd
import numpy as np
from DecisionTree import DecisionTree

c:\users\tony\appdata\local\programs\python\python36\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


## Read

In [5]:
## read train data
data = pd.read_table('training.txt', sep=' ', header=None)
# name label
data.rename(columns={0:'label'}, inplace=True)
# sepearte labels
label = data.iloc[:, 0]

# remove index: from data
data = data.iloc[:, 1:].applymap(lambda x: x[x.find(':')+1:])

# rename columns and merge label
data.columns = list(range(data.shape[1]))
data = data.join(label)
# label: int, other columns: str

In [38]:
## read test data
test = pd.read_table('testing.txt', sep=' ', header=None)

# remove index: from data
test = test.applymap(lambda x: x[x.find(':')+1:])

## Tuning

In [6]:
# train test split
n = data.shape[0]
idx = np.random.randint(0, n, int(n/20))
val_data = data.iloc[idx,:]
train_data = data.drop(idx)

# data indexing
train_data.index = range(0, train_data.shape[0])
val_data.index = range(0, val_data.shape[0])

In [51]:
%%time
max_depth = 10
threshold = 1e-4
min_node = 5
min_leaf = 3
dt = DecisionTree(max_depth, min_node, min_leaf, threshold)
dt.build(train_data)

Wall time: 1min 58s


In [53]:
pred = dt.predict(train_data)
print(np.mean(train_data.label == pred))

72 1, 1
(array([1, 2, 3, 4], dtype=int64), array([ 62, 206,  69, 259], dtype=int64))
56 3, 2
(array([1, 2, 3, 4], dtype=int64), array([ 8, 72, 20, 16], dtype=int64))
64 1, 2
(array([1, 2, 3, 4], dtype=int64), array([ 77, 135,  59, 181], dtype=int64))
79 3, 3
(array([1, 2, 3, 4], dtype=int64), array([ 3,  5, 12,  3], dtype=int64))
42 1, 3
(array([1, 2, 3, 4], dtype=int64), array([ 15,  22,   3, 102], dtype=int64))
23 3, 3
(array([1, 2, 3, 4], dtype=int64), array([ 4, 41, 23,  8], dtype=int64))
29 3, 3
(array([1, 2, 3, 4], dtype=int64), array([159,  46,  55,  88], dtype=int64))
None None, None
36 1, 4
(array([1, 2, 3, 4], dtype=int64), array([3, 6, 3, 6], dtype=int64))
35 3, 4
(array([1, 2, 3, 4], dtype=int64), array([4, 7, 1, 4], dtype=int64))
None None, None
8 3, 4
(array([2, 3, 4], dtype=int64), array([ 5, 12,  1], dtype=int64))
19 1, 4
(array([1, 2, 3, 4], dtype=int64), array([24, 10,  4, 66], dtype=int64))
69 3, 4
(array([1, 2, 3, 4], dtype=int64), array([18, 20,  8, 37], dtype=int6

## Save

In [42]:
dt = DecisionTree(max_depth=max_depth, min_node=min_node, min_leaf=min_leaf, threshold = threshold)
dt.build(data)
pred = dt.predict(test)

72 1, 1
(array([1, 2, 3, 4], dtype=int64), array([ 67, 217,  74, 268], dtype=int64))
56 3, 2
(array([1, 2, 3, 4], dtype=int64), array([ 8, 77, 20, 17], dtype=int64))
64 1, 2
(array([1, 2, 3, 4], dtype=int64), array([ 82, 141,  63, 189], dtype=int64))
82 1, 3
(array([1, 2, 3], dtype=int64), array([ 4,  6, 11], dtype=int64))
42 1, 3
(array([1, 2, 3, 4], dtype=int64), array([ 18,  24,   3, 107], dtype=int64))
23 3, 3
(array([1, 2, 3, 4], dtype=int64), array([ 4, 41, 23,  8], dtype=int64))
29 3, 3
(array([1, 2, 3, 4], dtype=int64), array([166,  46,  59,  97], dtype=int64))
15 3, 4
(array([1, 2, 3], dtype=int64), array([ 2,  1, 10], dtype=int64))
93 2, 4
(array([1, 2, 3, 4], dtype=int64), array([ 3, 54,  5,  4], dtype=int64))
84 1, 4
(array([1, 2, 4], dtype=int64), array([ 9, 10, 11], dtype=int64))
None None, None
8 3, 4
(array([2, 3, 4], dtype=int64), array([ 5, 12,  1], dtype=int64))
1 3, 4
(array([1, 2, 3, 4], dtype=int64), array([ 2, 27,  8, 10], dtype=int64))
99 3, 4
(array([1, 2, 3, 4

In [52]:
np.unique(pred, return_counts=True)

(array([1, 2, 3, 4], dtype=object), array([161,  94, 511, 234], dtype=int64))

In [23]:
with open('result.txt', 'w') as fp:
    [fp.write(str(predict)+'\n') for predict in pred]

## Test

In [1]:
from sklearn.tree import DecisionTreeClassifier

In [7]:
%%time
dt = DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=20,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=30,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
dt.fit(train_data.iloc[:,:-1], train_data.label)
pred = dt.predict(train_data.iloc[:,:-1])
np.mean(pred ==train_data.label)

Wall time: 288 ms
